# Generated by Django 2.2.4 on 2019-09-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=16, verbose_name='模块')),
                ('url', models.CharField(max_length=1000, verbose_name='URL')),
                ('run', models.CharField(max_length=3, verbose_name='是否运行')),
                ('req', models.CharField(max_length=8, verbose_name='请求类型')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'case',
            },
        ),
    ]
